import torch
from torch import nn


class Basic_Layer(nn.Module):
    """
    Basic 2D convolution block with BatchNorm, ReLU, and optional residual path.

    This layer is used as a simple building block for temporal layers.

    Input shape:
        x: [B, C_in, T, V]

        B     = batch size
        C_in  = input channels
        T     = temporal length, number of frames or selected keyframes
        V     = number of graph nodes, usually facial landmarks

    Output shape:
        x: [B, C_out, T, V]

    Main operation:
        output = ReLU(BN(Conv2D(x)) + residual(x))
    """

    def __init__(self, args, in_channel, out_channel, residual):
        super(Basic_Layer, self).__init__()

        self.conv = nn.Conv2d(in_channel, out_channel, kernel_size=1, bias=args.bias)

        self.out_channel = out_channel
        self.bn = nn.BatchNorm2d(out_channel)

        # If residual=True, use identity mapping.
        # If residual=False, use Zero_Layer so the block has no skip connection.
        self.residual = nn.Identity() if residual else Zero_Layer()

        self.act = nn.ReLU(inplace=True)

    def forward(self, x):
        """
        Forward pass.

        Args:
            x:
                Input tensor with shape [B, C_in, T, V].

        Returns:
            Tensor with shape [B, C_out, T, V].
        """

        res = self.residual(x)
        x = self.conv(x)
        x = self.bn(x)
        x = x + res
        x = self.act(x)

        return x


class Spatial_Graph_Layer(nn.Module):
    """
    Spatial graph convolution layer for facial landmark graph modeling.

    This layer performs two main operations:

        1. Channel projection using a 1 x 1 convolution.
        2. Graph aggregation using the given adjacency matrix.

    It supports both fixed adjacency matrices and batch-wise dynamic adjacency
    matrices generated by the STGAE decoder.

    Input:
        x:
            Tensor with shape [B, C_in, T, V]

            B     = batch size
            C_in  = input channel dimension
            T     = number of frames or selected keyframes
            V     = number of graph nodes, usually 51 facial landmarks

        Adj:
            Graph adjacency matrix.

            Supported shapes:

            1. [V, V]
                A single fixed adjacency matrix shared by all samples and all
                graph partitions.

            2. [K, V, V]
                A fixed multi-partition adjacency matrix.

                K = self.s_kernel_size = max_graph_distance + 1

            3. [B, V, V]
                A batch-wise dynamic adjacency matrix.

                This is the expected output shape of the updated EdgePredictor
                decoder:

                    DA.shape = [B, V, V]

            4. [B, K, V, V]
                A batch-wise dynamic multi-partition adjacency matrix.

    Output:
        Tensor with shape [B, C_out, T, V]

    Notes:
        The 1 x 1 convolution produces K groups of output features:

            [B, C_out * K, T, V]

        Then the tensor is reshaped to:

            [B, K, C_out, T, V]

        After graph aggregation over the node dimension, the output becomes:

            [B, C_out, T, V]

    Important:
        For the STGAE dynamic adjacency matrix from the paper, the most
        important supported case is:

            Adj.shape = [B, V, V]

        In that case, graph aggregation is performed using:

            torch.einsum("bkctv,bvw->bctw", x, Adj)
    """

    def __init__(
        self, args, in_channel, out_channel, max_graph_distance, residual=True
    ):
        super(Spatial_Graph_Layer, self).__init__()

        # Number of graph partitions.
        # In ST-GCN style models, this is commonly max_graph_distance + 1.
        self.s_kernel_size = max_graph_distance + 1

        # Project input channels into K groups of output channels.
        #
        # Input:
        #     [B, C_in, T, V]
        #
        # Output:
        #     [B, C_out * K, T, V]
        self.gcn = nn.Conv2d(
            in_channel, out_channel * self.s_kernel_size, kernel_size=1, bias=args.bias
        )

        # Residual connection.
        #
        # Case 1:
        #     residual=False
        #     No residual connection is used.
        #
        # Case 2:
        #     residual=True and C_in != C_out
        #     Use 1 x 1 convolution to match channel dimensions.
        #
        # Case 3:
        #     residual=True and C_in == C_out
        #     Use identity mapping.
        if not residual:
            self.residual = Zero_Layer()

        elif in_channel != out_channel:
            self.residual = nn.Sequential(
                nn.Conv2d(in_channel, out_channel, kernel_size=1, bias=args.bias),
                nn.BatchNorm2d(out_channel),
            )

        else:
            self.residual = nn.Identity()

        self.bn = nn.BatchNorm2d(out_channel)
        self.act = nn.ReLU(inplace=True)

    def forward(self, x, Adj):
        """
        Forward pass of the spatial graph layer.

        Args:
            x:
                Input tensor with shape [B, C_in, T, V].

            Adj:
                Adjacency matrix.

                Typical shape for fixed graph:
                    [V, V]

                Typical shape for STGAE dynamic graph:
                    [B, V, V]

        Returns:
            Tensor with shape [B, C_out, T, V].
        """

        # Save residual before modifying x.
        res = self.residual(x)

        # Channel projection.
        x = self.gcn(x)

        # Current shape:
        #     [B, C_out * K, T, V]
        B, KC, T, V = x.size()

        # Check whether the projected channel dimension can be split into K
        # graph partitions.
        if KC % self.s_kernel_size != 0:
            raise ValueError(
                f"Invalid channel size. Got KC={KC}, but it must be divisible "
                f"by s_kernel_size={self.s_kernel_size}."
            )

        C = KC // self.s_kernel_size

        # Split channels into graph partitions.
        #
        # Shape:
        #     [B, C_out * K, T, V]
        #         -> [B, K, C_out, T, V]
        x = x.view(B, self.s_kernel_size, C, T, V)

        # ------------------------------------------------------------
        # Graph aggregation
        # ------------------------------------------------------------

        if Adj.dim() == 2:
            # --------------------------------------------------------
            # Case 1: fixed single adjacency
            # Adj shape: [V, V]
            # --------------------------------------------------------
            if Adj.size(0) != V or Adj.size(1) != V:
                raise ValueError(
                    f"Adj shape mismatch. Expected [V, V] with V={V}, "
                    f"but got {tuple(Adj.shape)}."
                )

            # Same adjacency is used for every batch sample and every graph
            # partition.
            #
            # x:
            #     [B, K, C, T, V]
            #
            # Adj:
            #     [V, V]
            #
            # output:
            #     [B, C, T, V]
            x = torch.einsum("bkctv,vw->bctw", x, Adj)

        elif Adj.dim() == 3 and Adj.size(0) == self.s_kernel_size:
            # --------------------------------------------------------
            # Case 2: fixed multi-partition adjacency
            # Adj shape: [K, V, V]
            # --------------------------------------------------------
            if Adj.size(1) != V or Adj.size(2) != V:
                raise ValueError(
                    f"Adj shape mismatch. Expected [K, V, V] with "
                    f"K={self.s_kernel_size}, V={V}, but got {tuple(Adj.shape)}."
                )

            # Each graph partition has its own adjacency matrix.
            #
            # x:
            #     [B, K, C, T, V]
            #
            # Adj:
            #     [K, V, V]
            #
            # output:
            #     [B, C, T, V]
            x = torch.einsum("bkctv,kvw->bctw", x, Adj)

        elif Adj.dim() == 3:
            # --------------------------------------------------------
            # Case 3: batch-wise dynamic adjacency
            # Adj shape: [B, V, V]
            # --------------------------------------------------------
            if Adj.size(0) != B or Adj.size(1) != V or Adj.size(2) != V:
                raise ValueError(
                    f"Dynamic Adj shape mismatch. Expected [B, V, V] with "
                    f"B={B}, V={V}, but got {tuple(Adj.shape)}."
                )

            # Each sample has its own dynamic adjacency matrix.
            # The same dynamic adjacency is used across all K graph partitions.
            #
            # This is the main case for the STGAE dynamic adjacency matrix.
            #
            # x:
            #     [B, K, C, T, V]
            #
            # Adj:
            #     [B, V, V]
            #
            # output:
            #     [B, C, T, V]
            x = torch.einsum("bkctv,bvw->bctw", x, Adj)

        elif Adj.dim() == 4:
            # --------------------------------------------------------
            # Case 4: batch-wise dynamic multi-partition adjacency
            # Adj shape: [B, K, V, V]
            # --------------------------------------------------------
            if (
                Adj.size(0) != B
                or Adj.size(1) != self.s_kernel_size
                or Adj.size(2) != V
                or Adj.size(3) != V
            ):
                raise ValueError(
                    f"Dynamic multi-partition Adj shape mismatch. Expected "
                    f"[B, K, V, V] with B={B}, K={self.s_kernel_size}, V={V}, "
                    f"but got {tuple(Adj.shape)}."
                )

            # Each sample and each graph partition has its own adjacency matrix.
            #
            # x:
            #     [B, K, C, T, V]
            #
            # Adj:
            #     [B, K, V, V]
            #
            # output:
            #     [B, C, T, V]
            x = torch.einsum("bkctv,bkvw->bctw", x, Adj)

        else:
            raise ValueError(
                f"Unsupported adjacency shape: {tuple(Adj.shape)}. "
                f"Expected one of [V, V], [K, V, V], [B, V, V], "
                f"or [B, K, V, V]."
            )

        # Normalize, add residual, then apply activation.
        x = self.bn(x)
        x = x + res
        x = self.act(x)

        return x


class Temporal_Basic_Layer(Basic_Layer):
    """
    Basic temporal convolution layer.

    This layer applies convolution along the temporal dimension only.
    The landmark dimension is preserved.

    Input shape:
        x: [B, C, T, V]

    Output shape:
        x: [B, C, T_out, V]

    Temporal convolution kernel:
        [temporal_window_size, 1]

    If stride > 1:
        The temporal length T is reduced.

    If residual=True and stride != 1:
        The residual branch also uses stride so that the residual tensor has
        the same temporal shape as the main branch.
    """

    def __init__(self, args, channel, temporal_window_size, stride=1, residual=True):
        super(Temporal_Basic_Layer, self).__init__(args, channel, channel, residual)

        padding = (temporal_window_size - 1) // 2

        self.conv = nn.Conv2d(
            channel,
            channel,
            kernel_size=(temporal_window_size, 1),
            stride=(stride, 1),
            padding=(padding, 0),
            bias=args.bias,
        )

        if residual and stride != 1:
            self.residual = nn.Sequential(
                nn.Conv2d(
                    channel, channel, kernel_size=1, stride=(stride, 1), bias=args.bias
                ),
                nn.BatchNorm2d(channel),
            )


class Temporal_Bottleneck_Layer(nn.Module):
    """
    Temporal bottleneck convolution layer.

    This layer reduces the channel dimension, applies temporal convolution,
    and then restores the original channel dimension.

    Structure:
        x
        -> 1 x 1 reduction convolution
        -> temporal convolution
        -> 1 x 1 expansion convolution
        -> residual addition
        -> activation

    Input shape:
        x: [B, C, T, V]

    Output shape:
        x: [B, C, T_out, V]

    Args:
        channel:
            Input and output channel size.

        temporal_window_size:
            Kernel size along the temporal dimension.

        reduct_ratio:
            Channel reduction ratio.

            inner_channel = channel // reduct_ratio

        stride:
            Temporal stride.

        residual:
            Whether to use residual connection.
    """

    def __init__(
        self,
        channel,
        temporal_window_size,
        bias,
        act,
        reduct_ratio,
        stride=1,
        residual=True,
        **kwargs,
    ):
        super(Temporal_Bottleneck_Layer, self).__init__()

        inner_channel = channel // reduct_ratio
        padding = (temporal_window_size - 1) // 2

        self.act = act

        self.reduct_conv = nn.Sequential(
            nn.Conv2d(channel, inner_channel, kernel_size=1, bias=bias),
            nn.BatchNorm2d(inner_channel),
        )

        self.conv = nn.Sequential(
            nn.Conv2d(
                inner_channel,
                inner_channel,
                kernel_size=(temporal_window_size, 1),
                stride=(stride, 1),
                padding=(padding, 0),
                bias=bias,
            ),
            nn.BatchNorm2d(inner_channel),
        )

        self.expand_conv = nn.Sequential(
            nn.Conv2d(inner_channel, channel, kernel_size=1, bias=bias),
            nn.BatchNorm2d(channel),
        )

        if not residual:
            self.residual = Zero_Layer()

        elif stride == 1:
            self.residual = nn.Identity()

        else:
            self.residual = nn.Sequential(
                nn.Conv2d(
                    channel, channel, kernel_size=1, stride=(stride, 1), bias=bias
                ),
                nn.BatchNorm2d(channel),
            )

    def forward(self, x):
        """
        Forward pass.

        Args:
            x:
                Input tensor with shape [B, C, T, V].

        Returns:
            Tensor with shape [B, C, T_out, V].
        """

        res = self.residual(x)

        x = self.reduct_conv(x)
        x = self.act(x)

        x = self.conv(x)
        x = self.act(x)

        x = self.expand_conv(x)
        x = x + res
        x = self.act(x)

        return x


class Temporal_Sep_Layer(nn.Module):
    """
    Temporal separable convolution layer.

    This layer uses depthwise temporal convolution followed by pointwise
    convolution. It is more parameter-efficient than a standard temporal
    convolution.

    Optional structure:
        x
        -> optional 1 x 1 expansion convolution
        -> depthwise temporal convolution
        -> 1 x 1 pointwise convolution
        -> residual addition

    Input shape:
        x: [B, C, T, V]

    Output shape:
        x: [B, C, T_out, V]

    Args:
        expand_ratio:
            If expand_ratio > 0, the channel dimension is expanded before
            depthwise temporal convolution.

            inner_channel = channel * expand_ratio

            If expand_ratio <= 0, no expansion is applied.
    """

    def __init__(
        self,
        channel,
        temporal_window_size,
        bias,
        act,
        expand_ratio,
        stride=1,
        residual=True,
        **kwargs,
    ):
        super(Temporal_Sep_Layer, self).__init__()

        padding = (temporal_window_size - 1) // 2

        self.act = act

        if expand_ratio > 0:
            inner_channel = channel * expand_ratio

            self.expand_conv = nn.Sequential(
                nn.Conv2d(channel, inner_channel, kernel_size=1, bias=bias),
                nn.BatchNorm2d(inner_channel),
            )
        else:
            inner_channel = channel
            self.expand_conv = None

        self.depth_conv = nn.Sequential(
            nn.Conv2d(
                inner_channel,
                inner_channel,
                kernel_size=(temporal_window_size, 1),
                stride=(stride, 1),
                padding=(padding, 0),
                groups=inner_channel,
                bias=bias,
            ),
            nn.BatchNorm2d(inner_channel),
        )

        self.point_conv = nn.Sequential(
            nn.Conv2d(inner_channel, channel, kernel_size=1, bias=bias),
            nn.BatchNorm2d(channel),
        )

        if not residual:
            self.residual = Zero_Layer()

        elif stride == 1:
            self.residual = nn.Identity()

        else:
            self.residual = nn.Sequential(
                nn.Conv2d(
                    channel, channel, kernel_size=1, stride=(stride, 1), bias=bias
                ),
                nn.BatchNorm2d(channel),
            )

    def forward(self, x):
        """
        Forward pass.

        Args:
            x:
                Input tensor with shape [B, C, T, V].

        Returns:
            Tensor with shape [B, C, T_out, V].
        """

        res = self.residual(x)

        if self.expand_conv is not None:
            x = self.expand_conv(x)
            x = self.act(x)

        x = self.depth_conv(x)
        x = self.act(x)

        x = self.point_conv(x)

        x = x + res

        return x


class Temporal_SG_Layer(nn.Module):
    """
    Temporal separable graph-style layer.

    This layer combines depthwise temporal convolution and pointwise channel
    projection in a lightweight sequence.

    Structure:
        x
        -> depthwise temporal convolution
        -> pointwise channel reduction
        -> pointwise channel expansion
        -> depthwise temporal convolution
        -> residual addition

    Input shape:
        x: [B, C, T, V]

    Output shape:
        x: [B, C, T_out, V]

    Args:
        reduct_ratio:
            Channel reduction ratio.

            inner_channel = channel // reduct_ratio

        stride:
            Temporal stride used in the second depthwise temporal convolution.
    """

    def __init__(
        self,
        channel,
        temporal_window_size,
        bias,
        act,
        reduct_ratio,
        stride=1,
        residual=True,
        **kwargs,
    ):
        super(Temporal_SG_Layer, self).__init__()

        padding = (temporal_window_size - 1) // 2
        inner_channel = channel // reduct_ratio

        self.act = act

        self.depth_conv1 = nn.Sequential(
            nn.Conv2d(
                channel,
                channel,
                kernel_size=(temporal_window_size, 1),
                stride=1,
                padding=(padding, 0),
                groups=channel,
                bias=bias,
            ),
            nn.BatchNorm2d(channel),
        )

        self.point_conv1 = nn.Sequential(
            nn.Conv2d(channel, inner_channel, kernel_size=1, bias=bias),
            nn.BatchNorm2d(inner_channel),
        )

        self.point_conv2 = nn.Sequential(
            nn.Conv2d(inner_channel, channel, kernel_size=1, bias=bias),
            nn.BatchNorm2d(channel),
        )

        self.depth_conv2 = nn.Sequential(
            nn.Conv2d(
                channel,
                channel,
                kernel_size=(temporal_window_size, 1),
                stride=(stride, 1),
                padding=(padding, 0),
                groups=channel,
                bias=bias,
            ),
            nn.BatchNorm2d(channel),
        )

        if not residual:
            self.residual = Zero_Layer()

        elif stride == 1:
            self.residual = nn.Identity()

        else:
            self.residual = nn.Sequential(
                nn.Conv2d(
                    channel, channel, kernel_size=1, stride=(stride, 1), bias=bias
                ),
                nn.BatchNorm2d(channel),
            )

    def forward(self, x):
        """
        Forward pass.

        Args:
            x:
                Input tensor with shape [B, C, T, V].

        Returns:
            Tensor with shape [B, C, T_out, V].
        """

        res = self.residual(x)

        x = self.depth_conv1(x)
        x = self.act(x)

        x = self.point_conv1(x)

        x = self.point_conv2(x)
        x = self.act(x)

        x = self.depth_conv2(x)

        x = x + res

        return x


class Zero_Layer(nn.Module):
    """
    Zero residual layer.

    This layer is used when residual=False.

    Instead of passing the input through a residual branch, it returns 0.
    Therefore, the main branch output is used without skip connection.

    Example:
        output = main_branch(x) + Zero_Layer(x)
        output = main_branch(x) + 0
    """

    def __init__(self):
        super(Zero_Layer, self).__init__()

    def forward(self, x):
        """
        Return zero for residual suppression.

        Args:
            x:
                Input tensor. It is unused.

        Returns:
            Integer 0.

        Note:
            Returning 0 works with tensor addition in PyTorch.
        """

        return 0
